### ISSUE TITLE
Refactor social list variant adding correct CSS automatically

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/design-team#72]
Would be a good idea to refactor the social list variant so that the css that is related to it is set automatically when using a social icon. Currently some examples using them have this set and some not so there is some inconsistencies. This will also make the config a bit simpler for the user they will just need to set the icon and the rest will take care of itself.
I don't think this ever should've been a variant as the css is mandatory to get the alignment of the text right when using the social icons and is not really a list variant more that when using one of the social icons instead of any other icon we need to align the text so this is why I think it would be good to set this automatically for the user.

The changes that need to be made have been reverted in [this commit](https://github.com/ONSdigital/design-system/pull/3218/commits/5ec93079561a3855b48761c5be695d00ee5d167a)

**Comment by e-livingstone** [comment]
@rmccar to confirm if this is still required

**Comment by rmccar** [comment]
This has already been addressed in https://github.com/ONSdigital/design-system/pull/3262
